# config
cover: /img/bg_img.jpg
logo: /img/logo.jpg
top_saying:
- title: 欢迎来到我的博客空间。
- content: “对我来说，博客首先是一种知识管理工具，其次才是传播工具。我的技术文章，主要用来整理我还不懂的知识。我只写那些我还没有完全掌握的东西，那些我精通的东西，往往没有动力写。炫耀从来不是我的动机，好奇才是。” ——阮一峰
bottom_saying: 如果对本博客空间有什么建议或意见，请通过邮箱联系我：<a href="mailto:i@myliangxu.cn">i@myliangxu.cn</a>
# Content
excerpt_link: 更多

# rss: /atom.xml

highlightjs: github

#Works
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
duoshuo: myliangxu

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/lx3133584
qq: http://sighttp.qq.com/authd?IDKEY=ad9f4bb6d491cb8a1a45d2810f1d27c0ae03f775c0281130
weibo: http://weibo.com/u/3178976734

#about  timeline
timeline:
- num: 1
  word: 2017/03/31-建立本博客空间。
- num: 2
  word: 2017/04/01-把旧博客的东西搬运过来。
- num: 3
  word: 2015/04/02-建立about页面，把时间线记录在页面上。
- num: 4
  word: More

#Links
# links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/