# config
cover: /img/bg_img.jpg
logo: /img/logo.jpg
top_saying:
- title: 欢迎来到我的博客空间。
- content: “对我来说，博客首先是一种知识管理工具，其次才是传播工具。我的技术文章，主要用来整理我还不懂的知识。我只写那些我还没有完全掌握的东西，那些我精通的东西，往往没有动力写。炫耀从来不是我的动机，好奇才是。” --阮一峰
bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: github

#Works
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
duoshuo: 我就是那只松鼠

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/lx3133584
qq: http://sighttp.qq.com/authd?IDKEY=ad9f4bb6d491cb8a1a45d2810f1d27c0ae03f775c0281130
google: https://google.com/
weibo: http://weibo.com/u/3178976734

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
# links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/